### ISSUE TITLE
'FlutterKbzKitPlugin.h' file not found

### ISSUE THREAD

**Issue by nannmon2023** [Lolliwin/flutter_kpay_kit#2]
<img width="998" alt="Screenshot 2024-03-13 at 2 11 28 PM" src="https://github.com/WinKoKo91/flutter_kpay_kit/assets/151108507/31dc22a6-5e07-4cca-9dbc-707e640b40ba">
'FlutterKbzKitPlugin.h' file not found
I faced this error in ios app.Could you give me any solution for this?

**Comment by WinKoKo91** [comment]
Hello nannmon2023,

flutter_kpay_kit is not needed to try kbz pay. 
Cuz KBZ use deeplink to open their app and don't need any lib or package.

So this package is not support for current and coming KBZ pay.
And I will terminate this package soon.

Please contact and ask KBZ pay support to get Token.
